name = "MatLang"
uuid = "05b439c0-bb3c-11e9-1d8d-1f0a9ebca87a"
authors = ["aminya <aminyahyaabadi74@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[deps]
Requires="ae029012-a4dd-5104-9daa-d747884805df"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
